- type: gameMapPool
  id: DefaultMapPool
  maps:
  - roid_outpost
  - Amber
  - Elkridge
  - Glacier
  - Omega
  - Cluster
  - Box
  - Bagel
  - Barratry
  - Fland
  - Marathon
  - Meta
  #- Relic ## Essa porra de mapa é cursed demais
  - Saltern
  - Core


