- type: job
  id: CentralCommandOperador
  name: job-name-centcomope
  description: job-description-centcomope
  playTimeTracker: JobCentralCommandOperador
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Dignitary
    min: 108000 # 30 horas
  - !type:CharacterOverallTimeRequirement
    min: 216000 #60 horas
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
  setPreference: true
  startingGear: CentcomOperadorGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-dcc
  canBeAntag: false
  requireAdminNotify: true
  whitelisted: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 10
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: CentcomOperadorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOperador
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatBeretCentcomm
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: BoxFolderCentComClipboard
    pocket1: WeaponPistolN1984
    pocket2: MindShieldImplanter
